name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --silent -e mks_robin_nano_v1_3_f4
        
      - name: Move binary
        run: mv .pio/build/mks_robin_nano_v1_3_f4/firmware.bin config/Elegoo/Neptune-2/V1.3/BLTOUCH/elegoo.bin
